name: Test

on:
  pull_request:
    types: [labeled]
    branches:
      - '*'

jobs:
  test_pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run ruby script
        run: ruby ./test.rb
        if: contains( github.event.label.name, 'runtests')
